module.exports = {
	// breakpoints
	breakpoint_small: "640px",
	breakpoint_medium: "960px",
	breakpoint_large: "1200px",
	breakpoint_xlarge: "1600px",
	// backgrounds
	global_background: "#fff",
	global_muted_background: "#f8f8f8",
	global_primary_background: "#1e87f0",
	global_secondary_background: "#222",
	global_success_background: "#32d296",
	global_warning_background: "#faa05a",
	global_danger_background: "#f0506e",
	// colors
	global_color: "#666",
	global_emphasis_color: "#333",
	global_muted_color: "#999",
	global_link_color: "#1e87f0",
	global_link_hover_color: "#0f6ecd",
	global_inverse_color: "#fff",
	// fonts
	global_font_size: "16px",
	global_line_height: "1.5",
	global_2xlarge_font_size: "2.625rem",
	global_xlarge_font_size: "2rem",
	global_large_font_size: "1.5rem",
	global_medium_font_size: "1.25rem",
	global_small_font_size: "0.875rem",
};
