title: Nav Block
status: wip
default: nav-block
meta:
    placement: []
    group: header
    tags:
        - collection
        - multiple
        - icons
    config:
        - background
        - container
        - spacing
    fields:
        - logo
        - primary
context:
    logo:
        url: "#"
        src: https://assets.uiaas.io/web/placeholder-logo.svg
        label:
        tagline:
    primary:
        - label: Products
          url: "#"
          external:
          main:
              items:
                  - title:
                    description:
                    mode: main
                    ctas:
                        - label: Product 1
                          description:
                          image:
                          icon: https://assets.uiaas.io/web/users/aviso/product-icon-color.png
                          url: "#"
                          external: false
                        - label: Product 2
                          description:
                          image:
                          icon: https://assets.uiaas.io/web/users/aviso/product-icon-color.png
                          url: "#"
                          external: false
                        - label: Product 3
                          description: sdfjknsd fjnsdfjnsd zdfds fs df sdfs dfsdfddf
                          image:
                          icon: https://assets.uiaas.io/web/users/aviso/product-icon-color.png
                          url: "#"
                          external: false
                        - label: Product 4
                          description: sdfjknsd fjnsdfjnsd fjnsdfjnsd zdfds fs df sdfs dfsdfddf
                          image:
                          icon: https://assets.uiaas.io/web/users/aviso/product-icon-color.png
                          url: "#"
                          external: false
                        - label: Product 1
                          description: sdfjknsd fjnsdfjnsd fjnsdfjnsd zdfds fs df sdfs dfsdfddf
                          image:
                          icon: https://assets.uiaas.io/web/users/aviso/product-icon-color.png
                          url: "#"
                          external: false
                        - label: Product 2
                          description: sdfjknsd fjnsdfjnsd fjnsdfjnsd zdfds fs df sdfs
                          image:
                          icon: https://assets.uiaas.io/web/users/aviso/product-icon-color.png
                          url: "#"
                          external: false
                        - label: Product 3
                          description: sdfjknsd fjnsdfjnsd
                          image:
                          icon: https://assets.uiaas.io/web/users/aviso/product-icon-color.png
                          url: "#"
                          external: false
                        - label: Product 4
                          description: sdfjknsd fjnsdfjnsd
                          image:
                          icon:
                          url: "#"
                          external: false
          side:
              items:
                  - title: Aviso Platform
                    description: The AI operating system that scales with your business
                    icon: https://assets.uiaas.io/web/users/aviso/product-icon-color.png
                    image:
                    ctas:
                        - label: Learn more
                          url: "/platform"
                          external:
          style:
              columns: 2
        - label: Resources
          url: "#"
          external:
          links:
              - label: Resource 1
                url: "#"
                external: false
              - label: Resource 2
                url: "#"
                external: false
        - label: Features
          url: "#"
          external:
        - label: About
          url: "#"
          external:
        - label: Company
          url: "#"
          external:
    secondary:
        - label: Blog
          url: "#"
          external:
          links:
        - label: Support
          url: "#"
          external:
          links:
    social:
        - label: facebook
          url: "#"
          external: true
        - label: twitter
          url: "#"
          external: true
        - label: linkedin
          url: "#"
          external: true
variants:
    - name: nav-block
      status: ready
      meta:
          placement: [0]
          group: header
          tags:
              - header
              - nav
              - logo
      context:
          logo:
              label: Awesome
              src:
          style:
              background: "#333"
              container: md
              spacing: xxs
              justify: left
              align: left
    - name: simple-header
      status: ready
      meta:
          placement: [0]
          group: header
          tags:
              - header
              - nav
              - logo
              - social
      context:
          style:
              background: "#f8f9f3"
              container: md
              spacing: xxs
              justify: between
              align: left
          logo:
              label:
              src: https://assets.uiaas.io/web/placeholder-logo.svg
    - name: subnav
      status: ready
      meta:
          placement: [0]
          group: header
          tags:
              - header
              - nav
              - logo
              - social
      context:
          style:
              background: "#f8f9f3"
              container: md
              spacing: xxs
              justify: between
              align: left
          logo:
              label: Product Name
              src:
    - name: header-with-secondary-nav
      status: ready
      meta:
          placement: [0]
          group: header
          tags:
              - header
              - nav
              - logo
              - social
          fields:
              - logo
              - primary
              - secondary
      context:
          ctas: "@utils.buttons.sm"
          style:
              background: "#fff"
              justify: between
              align: left
              spacing: xs
    - name: header-two-tier
      status: ready
      meta:
          placement: [0]
          group: header
          tags:
              - header
              - nav
              - logo
              - social
          fields:
              - logo
              - primary
              - secondary
              - ctas
      context:
          ctas: "@utils.buttons.sm"
          style:
              background: "#f6f6f6"
              justify: between
              align: left
              spacing: xxs
    - name: header-two-tier-social
      status: ready
      meta:
          placement: [0]
          group: header
          tags:
              - header
              - nav
              - logo
              - social
          fields:
              - logo
              - primary
              - secondary
              - ctas
              - social
      context:
          style:
              background: "#f1f1f1"
              justify: between
              align: left
              spacing: xxs
    - name: header-two-tier-social-ctas
      status: ready
      meta:
          placement: [0]
          group: header
          tags:
              - header
              - nav
              - logo
              - social
          fields:
              - logo
              - primary
              - secondary
              - ctas
              - social
      context:
          ctas: "@utils.buttons.sm"
          style:
              background: "#f1f1f1"
              justify: between
              align: left
              spacing: xxs
    - name: simple-footer
      status: ready
      meta:
          placement: [0]
          group: footer
          tags:
              - footer
              - logo
              - social
          fields:
              - description
              - social
      context:
          description: "&copy;2021 Logo Inc. All Rights Reserved"
          ctas: "@utils.buttons.sm"
          style:
              background: "#333"
              justify: between
              align: left
              spacing: xs
              container:
    - name: footer-with-divider
      status: ready
      meta:
          placement: [0]
          group: footer
          tags:
              - footer
              - logo
              - social
          fields:
              - description
              - social
      context:
          description: "&copy;2021 Logo Inc. All Rights Reserved"
          style:
              background: "#fff"
              justify: between
              align: left
              spacing: sm
              container:
    - name: footer-with-links
      status: ready
      meta:
          placement: [0]
          group: footer
          tags:
              - footer
              - logo
              - social
          fields:
              - logo
              - description
              - primary
              - social
      context:
          description: "&copy;2021 Logo Inc. All Rights Reserved"
          style:
              background: "#fff"
              justify: between
              align: left
              spacing: sm
              container:
    - name: footer-with-links-max
      status: ready
      meta:
          placement: [0]
          group: footer
          tags:
              - footer
              - logo
              - social
          fields:
              - logo
              - description
              - primary
              - social
      context:
          description: "&copy;2021 Logo Inc. All Rights Reserved"
          style:
              background: "#fff"
              justify: between
              align: left
              spacing: sm
              container:
    - name: footer-tiered
      status: ready
      meta:
          placement: [0]
          group: footer
          tags:
              - footer
              - simple
              - tiered
              - social
          fields:
              - logo
              - description
              - primary
              - social
      context:
          description: "&copy;2021 Logo Inc. All Rights Reserved"
          style:
              background: "#333"
              justify: center
              align: center
              spacing: sm
              container:
